"""add post image table

Revision ID: 763a64432c0d
Revises: e14a75ca9cc3
Create Date: 2022-12-21 16:10:03.163004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763a64432c0d'
down_revision = 'e14a75ca9cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_images')
    # ### end Alembic commands ###
